CREATE TABLE PERSONS (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE FLATS (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price INT NOT NULL,
  area DECIMAL NOT NULL,
  description VARCHAR(1000) NOT NULL
);

CREATE TABLE RESERVATIONS (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rental_from DATE NOT NULL,
  rental_to DATE NOT NULL,
  total_cost INT NOT NULL,
  host_id BIGINT,
  FOREIGN KEY (host_id) REFERENCES PERSONS(id),
  tenant_id BIGINT,
  FOREIGN KEY (tenant_id) REFERENCES PERSONS(id),
  flat_id BIGINT,
  FOREIGN KEY (flat_id) REFERENCES FLATS(id)
);